[application]

# App (Project) Name
name = "scrow"

# The Dioxus platform to default to
default_platform = "web"

# `build` & `serve` output path
out_dir = "dist"

# The static resource path
asset_dir = "assets"

[web.app]
# HTML title tag content
title = "Satoshi Escrow"
